---
title: "Data normalization"
output:
  html_document:
    keep_md: yes
---
Required libraries:

[preprocessCore](http://www.bioconductor.org/packages/release/bioc/html/preprocessCore.html)
[ggplot2](http://docs.ggplot2.org/)

```{r}
library(GeoDE)
library(ggplot2)
library(scales) 
library(reshape2)
library(dplyr)
library(preprocessCore)
```

## Example data

```{r}
str(example_expression_data)

data(example_expression_data, package = "GeoDE")

ggplot(melt(example_expression_data), aes(x=value, col=variable)) + geom_density() + theme_bw()

ggplot(melt(example_expression_data), aes(x=value, col=genenames)) + geom_density() + theme_bw() + scale_x_log10() + guides(colour=FALSE)

example_expression_data_norm <- example_expression_data

example_expression_data_norm[, 2:7] <- t(apply(example_expression_data[, 2:7], 1, scale))

ggplot(melt(example_expression_data_norm), aes(x=value, col=genenames)) + geom_density() + theme_bw() + guides(colour=FALSE)
```



## Z-score Normalization

```{r}
original <- matrix(c(
    2,  4,  4,
    5,  4,  14,
    4,  6,  8,
    3,  5,  8,
    3,  3,  9
), ncol = 3, byrow = TRUE)
original
```


```{r}
means <- rowMeans(original)
stddevs <- apply(original, 1, sd)
cbind(means, stddevs)
```

```{r}
centered <- original - means
centered
```

```{r}
normalized <- centered / stddevs
normalized
```

```{r}
rowMeans(normalized)
apply(normalized, 1, sd)
```


## Quantile Normalization
```{r}

dn <- setNames(as.data.frame(preprocessCore::normalize.quantiles(as.matrix(d))), c('x', 'y'))

d <- data.frame(x=c(rep(1, 1000), rep(2000, 1000)), y=rnorm(2000))
d <- data.frame(x=rpois(2000, 1), y=rnorm(2000))


```

## Median Polish Normalization
```{r}
preprocessCore::rcModelMedianPolish(original)
```