---
title: "Data normalization"
output:
  html_document:
    keep_md: yes
---

```{r, message=FALSE}
library(GeoDE)
library(GEOquery)

library(preprocessCore)
library(reshape2)
library(dplyr)

library(ggplot2)
library(scales)
library(gridExtra)
```

## Loading dataset

```{r, message=FALSE}
gds3773 <- getGEO('GDS3773', GSEMatrix=TRUE)

```

## Basic information:

```{r}
Meta(gds3773)$platform_organism
Meta(gds3773)$description[1]
Meta(gds3773)$feature_count
Meta(gds3773)$sample_count
Meta(gds3773)$sample_type
Meta(gds3773)$platform_technology_type
Columns(gds3773)
```

## Convert data to numerics

```{r}
gds3773_data <- Table(gds3773)[, -1]

sampleclass <- factor(grepl('control', Columns(gds3773)$description), levels=c(TRUE, FALSE), labels=c('1', '2'))      
                      
gds3773_data [, -1] <- {
    apply(Table(gds3773)[, -c(1, 2)], 2, function(x) as.numeric(as.character(x)))
}

gds3773_data <- gds3773_data[complete.cases(gds3773_data), ]
```

## Plot "raw" data

```{r}
p <- ggplot(melt(gds3773_data, id.vars = 'IDENTIFIER'), aes(x = value, colour = variable))
p + geom_density(na.rm = TRUE) + theme_bw() + ggtitle('GDS3773')
```

## Normalize quantiles

```{r}
gds3773_data_normalized_quantiles <- gds3773_data
gds3773_data_normalized_quantiles[, -1] <- normalize.quantiles(as.matrix(gds3773_data[, -1]))

p <- ggplot(melt(gds3773_data_normalized_quantiles, id.vars = 'IDENTIFIER'), aes(x = value, colour = variable))
p + geom_density(na.rm = TRUE) + theme_bw() + ggtitle('GDS3773 Normalized quantiles')
```

## Median polish

```{r}
gds3773_data_median_polished <- gds3773_data
gds3773_data_median_polished[, -1] <- gds3773_data_median_polished[, -1] - {
    mp <- preprocessCore::rcModelMedianPolish(as.matrix(gds3773_data_normalized_quantiles[, -1]))
    mp$Residuals
}

p <- ggplot(melt(gds3773_data_median_polished, id.vars = 'IDENTIFIER'), aes(x = value, colour = variable))
p + geom_density(na.rm = TRUE) + theme_bw() + ggtitle('GDS3773 Median polished')
```

## Z-score normalize

```{r}
gds3773_z_score_normalized <- gds3773_data
gds3773_z_score_normalized[, -1] <- gds3773_z_score_normalized[, -1] - {
    rowmeans <- apply(gds3773_z_score_normalized[, -1], 1, mean)
    rowstds <- apply(gds3773_z_score_normalized[, -1], 1, sd)
    (gds3773_z_score_normalized[, -1] - rowmeans) / rowstds
}

p <- ggplot(melt(gds3773_z_score_normalized, id.vars = 'IDENTIFIER'), aes(x = value, colour = variable))
p + geom_density(na.rm = TRUE) + theme_bw() + ggtitle('GDS3773 Z-score normalized')
```


```{r}

gds3773_data <- gds3773_data[!grepl('control|^chr', gds3773_data$IDENTIFIER), ]
cd <- GeoDE::chdirAnalysis(na.omit(gds3773_data), sampleclass, nnull = 1000)
```


1. Ramadoss, P., Chiappini, F., Bilban, M. & Hollenberg, A. N. Regulation of hepatic six transmembrane epithelial antigen of prostate 4 (STEAP4) expression by STAT3 and CCAAT/enhancer-binding protein alpha. J. Biol. Chem. 285, 16453–16466 (2010).